server:
  port: 18001
eureka:
  instance:
    hostname: "eurekaServer18001"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/"
  server:
    enable-self-preservation: false

spring:
  application:
    name: Eureka

logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG